### ISSUE TITLE
html template for create event page

### ISSUE THREAD

**Issue by ninjaginja** [ninjaginja/Gather4Good#8]
create html shell for Create Event page with form:

*Event Title
*Event Description
*Cause
*Date/Time
*Location Name
*Street Address
*City
*State
*Zip
*Image url

**Comment by ninjaginja** [comment]
@kelsisummers I updated the 'id' and 'for' of the event description form field from 'textarea1' to 'event_description' to be consistent with the naming of the other fields.

**Comment by kelsisummers** [comment]
Okay! Sounds good. I changed it on mine as well. There was one line of javascript that needed to be updated as well for the character counter to work. I’ve done finishing touches on CSS and responsive, and pushed it to the create-event branch. It’s ready for review. :)

Thanks, Molly!

-Kelsi
